/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQGroupBox::MaxQGroupBox(BBObject * handle, const QString & title, QWidget * parent)
	: maxHandle(handle), QGroupBox(title, parent)
{
	qbind(this, handle);
}

MaxQGroupBox::~MaxQGroupBox()
{
	qunbind(this);
}

void MaxQGroupBox::onClicked(bool checked) {
	_qt_qgroupbox_QGroupBox__OnClicked(maxHandle, static_cast<int>(checked));
}

void MaxQGroupBox::onToggled(bool on) {
	_qt_qgroupbox_QGroupBox__OnToggled(maxHandle, static_cast<int>(on));
}

void MaxQGroupBox::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}

void MaxQGroupBox::timerEvent(QTimerEvent * event) {
	_qt_qobject_QObject__timerEvent(maxHandle, event);
}

// *********************************************

QGroupBox * bmx_qt_qgroupbox_create(BBObject * handle, BBString * title, QWidget * parent) {
	return new MaxQGroupBox(handle, qStringFromBBString(title), parent);
}

int bmx_qt_qgroupbox_alignment(QGroupBox * gb) {
	return gb->alignment();
}


int bmx_qt_qgroupbox_ischeckable(QGroupBox * gb) {
	return static_cast<int>(gb->isCheckable());
}


int bmx_qt_qgroupbox_ischecked(QGroupBox * gb) {
	return static_cast<int>(gb->isChecked());
}


int bmx_qt_qgroupbox_isflat(QGroupBox * gb) {
	return static_cast<int>(gb->isFlat());
}


void bmx_qt_qgroupbox_setalignment(QGroupBox * gb, int alignment) {
	gb->setAlignment(bmx_qt_getalignment(alignment));
}


void bmx_qt_qgroupbox_setcheckable(QGroupBox * gb, int checkable) {
	gb->setCheckable(static_cast<bool>(checkable));
}


void bmx_qt_qgroupbox_setflat(QGroupBox * gb, int flat) {
	gb->setFlat(static_cast<bool>(flat));
}


void bmx_qt_qgroupbox_settitle(QGroupBox * gb, BBString * title) {
	gb->setTitle(qStringFromBBString(title));
}


BBString * bmx_qt_qgroupbox_title(QGroupBox * gb) {
	return bbStringFromQString(gb->title());
}

void bmx_qt_qgroupbox_setchecked(QGroupBox * gb, int checked) {
	gb->setChecked(static_cast<bool>(checked));
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
