/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------



// *********************************************

int bmx_qt_qabstractslider_hastracking(QAbstractSlider * slider) {
	return static_cast<int>(slider->hasTracking());
}

int bmx_qt_qabstractslider_invertedappearance(QAbstractSlider * slider) {
	return static_cast<int>(slider->invertedAppearance());
}

int bmx_qt_qabstractslider_invertedcontrols(QAbstractSlider * slider) {
	return static_cast<int>(slider->invertedControls());
}

int bmx_qt_qabstractslider_issliderdown(QAbstractSlider * slider) {
	return static_cast<int>(slider->isSliderDown());
}

int bmx_qt_qabstractslider_maximum(QAbstractSlider * slider) {
	return slider->maximum();
}

int bmx_qt_qabstractslider_minimum(QAbstractSlider * slider) {
	return slider->minimum();
}

int bmx_qt_qabstractslider_orientation(QAbstractSlider * slider) {
	return slider->orientation();
}

int bmx_qt_qabstractslider_pagestep(QAbstractSlider * slider) {
	return slider->pageStep();
}

void bmx_qt_qabstractslider_setinvertedappearance(QAbstractSlider * slider, int value) {
	slider->setInvertedAppearance(static_cast<bool>(value));
}

void bmx_qt_qabstractslider_setinvertedcontrols(QAbstractSlider * slider, int value) {
	slider->setInvertedControls(static_cast<bool>(value));
}

void bmx_qt_qabstractslider_setmaximum(QAbstractSlider * slider, int value) {
	slider->setMaximum(value);
}

void bmx_qt_qabstractslider_setminimum(QAbstractSlider * slider, int value) {
	slider->setMinimum(value);
}

void bmx_qt_qabstractslider_setpagestep(QAbstractSlider * slider, int value) {
	slider->setPageStep(value);
}

void bmx_qt_qabstractslider_setrange(QAbstractSlider * slider, int minimum, int maximum) {
	slider->setRange(minimum, maximum);
}

void bmx_qt_qabstractslider_setsinglestep(QAbstractSlider * slider, int value) {
	slider->setSingleStep(value);
}

void bmx_qt_qabstractslider_setsliderdown(QAbstractSlider * slider, int value) {
	slider->setSliderDown(static_cast<bool>(value));
}

void bmx_qt_qabstractslider_setsliderposition(QAbstractSlider * slider, int value) {
	slider->setSliderPosition(value);
}

void bmx_qt_qabstractslider_settracking(QAbstractSlider * slider, int enable) {
	slider->setTracking(static_cast<bool>(enable));
}

int bmx_qt_qabstractslider_singlestep(QAbstractSlider * slider) {
	return slider->singleStep();
}

int bmx_qt_qabstractslider_sliderposition(QAbstractSlider * slider) {
	return slider->sliderPosition();
}

void bmx_qt_qabstractslider_triggeraction(QAbstractSlider * slider, int sliderAction) {
	slider->triggerAction((QAbstractSlider::SliderAction)sliderAction);
}

int bmx_qt_qabstractslider_value(QAbstractSlider * slider) {
	return slider->value();
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
