/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQDoubleSpinBox::MaxQDoubleSpinBox(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QDoubleSpinBox(parent)
{
	qbind(this, handle);
}

MaxQDoubleSpinBox::~MaxQDoubleSpinBox()
{
	qunbind(this);
}

void MaxQDoubleSpinBox::onValueChanged(double value) {
	_qt_qdoublespinbox_QDoubleSpinBox__OnValueChanged(maxHandle, value);
}

void MaxQDoubleSpinBox::onEditingFinished() {
	_qt_qabstractspinbox_QAbstractSpinBox__OnEditingFinished(maxHandle);
}

void MaxQDoubleSpinBox::customContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}


// *********************************************

QDoubleSpinBox * bmx_qt_qdoublespinbox_create(BBObject * handle, QWidget * parent) {
	return new MaxQDoubleSpinBox(handle, parent);
}

BBString * bmx_qt_qdoublespinbox_cleantext(QDoubleSpinBox * box) {
	return bbStringFromQString(box->cleanText());
}

int bmx_qt_qdoublespinbox_decimals(QDoubleSpinBox * box) {
	return box->decimals();
}


double bmx_qt_qdoublespinbox_maximum(QDoubleSpinBox * box) {
	return box->maximum();
}

double bmx_qt_qdoublespinbox_minimum(QDoubleSpinBox * box) {
	return box->minimum();
}

BBString * bmx_qt_qdoublespinbox_prefix(QDoubleSpinBox * box) {
	return bbStringFromQString(box->prefix());
}

void bmx_qt_qdoublespinbox_setdecimals(QDoubleSpinBox * box, int prec) {
	box->setDecimals(prec);
}


void bmx_qt_qdoublespinbox_setmaximum(QDoubleSpinBox * box, double value) {
	box->setMaximum(value);
}

void bmx_qt_qdoublespinbox_setminimum(QDoubleSpinBox * box, double value) {
	box->setMinimum(value);
}

void bmx_qt_qdoublespinbox_setprefix(QDoubleSpinBox * box, BBString * prefix) {
	box->setPrefix(qStringFromBBString(prefix));
}

void bmx_qt_qdoublespinbox_setrange(QDoubleSpinBox * box, double minimum, double maximum) {
	box->setRange(minimum, maximum);
}

void bmx_qt_qdoublespinbox_setsinglestep(QDoubleSpinBox * box, double val) {
	box->setSingleStep(val);
}

void bmx_qt_qdoublespinbox_setsuffix(QDoubleSpinBox * box, BBString * suffix) {
	box->setSuffix(qStringFromBBString(suffix));
}

double bmx_qt_qdoublespinbox_singlestep(QDoubleSpinBox * box) {
	return box->singleStep();
}

BBString * bmx_qt_qdoublespinbox_suffix(QDoubleSpinBox * box) {
	return bbStringFromQString(box->suffix());
}

double bmx_qt_qdoublespinbox_value(QDoubleSpinBox * box) {
	return box->value();
}


void bmx_qt_qdoublespinbox_setvalue(QDoubleSpinBox * box, double value) {
	box->setValue(value);
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
