/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQStatusBar::MaxQStatusBar(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QStatusBar(parent)
{
	qbind(this, handle);
}

MaxQStatusBar::~MaxQStatusBar()
{
	qunbind(this);
}


// *********************************************

QStatusBar * bmx_qt_qstatusbar_create(BBObject * handle, QWidget  * parent) {
	return new MaxQStatusBar(handle, parent);
}

void bmx_qt_qstatusbar_addpermanentwidget(QStatusBar * sb, QWidget * widget, int stretch) {
	sb->addPermanentWidget(widget, stretch);
}

void bmx_qt_qstatusbar_addwidget(QStatusBar * sb, QWidget * widget, int stretch) {
	sb->addWidget(widget, stretch);
}

BBString * bmx_qt_qstatusbar_currentmessage(QStatusBar * sb) {
	return bbStringFromQString(sb->currentMessage());
}

int bmx_qt_qstatusbar_insertpermanentwidget(QStatusBar * sb, int index, QWidget * widget, int stretch) {
	return sb->insertPermanentWidget(index, widget, stretch);
}

int bmx_qt_qstatusbar_insertwidget(QStatusBar * sb, int index, QWidget * widget, int stretch) {
	return sb->insertWidget(index, widget, stretch);
}

int bmx_qt_qstatusbar_issizegripenabled(QStatusBar * sb) {
	return static_cast<int>(sb->isSizeGripEnabled());
}

void bmx_qt_qstatusbar_removewidget(QStatusBar * sb, QWidget * widget) {
	sb->removeWidget(widget);
}

void bmx_qt_qstatusbar_setsizegripenabled(QStatusBar * sb, int value) {
	sb->setSizeGripEnabled(static_cast<bool>(value));
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
