/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQTextEdit::MaxQTextEdit(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QTextEdit(parent)
{
	qbind(this, handle);
}

MaxQTextEdit::~MaxQTextEdit()
{
	qunbind(this);
}


// *********************************************

QTextEdit * bmx_qt_qtextedit_create(BBObject * handle, QWidget * parent) {
	return new MaxQTextEdit(handle, parent);
}

void bmx_qt_qtextedit_setreadonly(QTextEdit * edit, int value) {
	edit->setReadOnly(static_cast<bool>(value));
}


void bmx_qt_qtextedit_append(QTextEdit * edit, BBString * text) {
	edit->append(qStringFromBBString(text));
}


void bmx_qt_qtextedit_clear(QTextEdit * edit) {
	edit->clear();
}


void bmx_qt_qtextedit_copy(QTextEdit * edit) {
	edit->copy();
}


void bmx_qt_qtextedit_cut(QTextEdit * edit) {
	edit->cut();
}


void bmx_qt_qtextedit_inserthtml(QTextEdit * edit, BBString * text) {
	edit->insertHtml(qStringFromBBString(text));
}


void bmx_qt_qtextedit_insertplaintext(QTextEdit * edit, BBString * text) {
	edit->insertPlainText(qStringFromBBString(text));
}


void bmx_qt_qtextedit_paste(QTextEdit * edit) {
	edit->paste();
}


void bmx_qt_qtextedit_redo(QTextEdit * edit) {
	edit->redo();
}


void bmx_qt_qtextedit_scrolltoanchor(QTextEdit * edit, BBString * name) {
	edit->scrollToAnchor(qStringFromBBString(name));
}


void bmx_qt_qtextedit_selectall(QTextEdit * edit) {
	edit->selectAll();
}


void bmx_qt_qtextedit_setalignment(QTextEdit * edit, int a) {
	edit->setAlignment(bmx_qt_getalignment(a));
}


void bmx_qt_qtextedit_setcurrentfont(QTextEdit * edit, MaxQFont * f) {
	edit->setCurrentFont(f->Font());
}


void bmx_qt_qtextedit_setfontfamily(QTextEdit * edit, BBString * fontFamily) {
	edit->setFontFamily(qStringFromBBString(fontFamily));
}


void bmx_qt_qtextedit_setfontitalic(QTextEdit * edit, int italic) {
	edit->setFontItalic(static_cast<bool>(italic));
}


void bmx_qt_qtextedit_setfontpointsize(QTextEdit * edit, double s) {
	edit->setFontPointSize(s);
}


void bmx_qt_qtextedit_setfontunderline(QTextEdit * edit, int underline) {
	edit->setFontUnderline(static_cast<bool>(underline));
}


void bmx_qt_qtextedit_setfontweight(QTextEdit * edit, int weight) {
	edit->setFontWeight(weight);
}


void bmx_qt_qtextedit_sethtml(QTextEdit * edit, BBString * text) {
	edit->setHtml(qStringFromBBString(text));
}


void bmx_qt_qtextedit_setplaintext(QTextEdit * edit, BBString * text) {
	edit->setPlainText(qStringFromBBString(text));
}


void bmx_qt_qtextedit_settext(QTextEdit * edit, BBString * text) {
	edit->setText(qStringFromBBString(text));
}


void bmx_qt_qtextedit_settextbackgroundcolor(QTextEdit * edit, MaxQColor * c) {
	edit->setTextBackgroundColor(c->Color());
}


void bmx_qt_qtextedit_settextcolor(QTextEdit * edit, MaxQColor * c) {
	edit->setTextColor(c->Color());
}


void bmx_qt_qtextedit_undo(QTextEdit * edit) {
	edit->undo();
}


void bmx_qt_qtextedit_zoomin(QTextEdit * edit, int _range) {
	edit->zoomIn(_range);
}


void bmx_qt_qtextedit_zoomout(QTextEdit * edit, int _range) {
	edit->zoomOut(_range);
}

BBString * bmx_qt_qtextedit_tohtml(QTextEdit * edit) {
	return bbStringFromQString(edit->toHtml());
}

BBString * bmx_qt_qtextedit_toplaintext(QTextEdit * edit) {
	return bbStringFromQString(edit->toPlainText());
}

QTextDocument * bmx_qt_qtextedit_document(QTextEdit * edit) {
	QTextDocument * doc = edit->document();
	MaxQTextDocument::link(doc);
	return doc;
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
