/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQSpinBox::MaxQSpinBox(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QSpinBox(parent)
{
	qbind(this, handle);

	connect(this, SIGNAL(valueChanged(int)), SLOT(onValueChanged(int)));
	connect(this, SIGNAL(editingFinished()), SLOT(onEditingFinished()));
	connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), SLOT(onCustomContextMenuRequested(const QPoint &)));
}

MaxQSpinBox::~MaxQSpinBox()
{
	qunbind(this);
}

void MaxQSpinBox::onValueChanged(int i) {
	_qt_qspinbox_QSpinBox__OnValueChanged(maxHandle, i);
}

void MaxQSpinBox::onEditingFinished() {
	_qt_qabstractspinbox_QAbstractSpinBox__OnEditingFinished(maxHandle);
}

void MaxQSpinBox::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}

// *********************************************

QSpinBox * bmx_qt_qspinbox_create(BBObject * handle, QWidget * parent) {
	return new MaxQSpinBox(handle, parent);
}

BBString * bmx_qt_qspinbox_cleantext(QSpinBox * box) {
	return bbStringFromQString(box->cleanText());
}

int bmx_qt_qspinbox_maximum(QSpinBox * box) {
	return box->maximum();
}

int bmx_qt_qspinbox_minimum(QSpinBox * box) {
	return box->minimum();
}

BBString * bmx_qt_qspinbox_prefix(QSpinBox * box) {
	return bbStringFromQString(box->prefix());
}

void bmx_qt_qspinbox_setmaximum(QSpinBox * box, int value) {
	box->setMaximum(value);
}

void bmx_qt_qspinbox_setminimum(QSpinBox * box, int value) {
	box->setMinimum(value);
}

void bmx_qt_qspinbox_setprefix(QSpinBox * box, BBString * prefix) {
	box->setPrefix(qStringFromBBString(prefix));
}

void bmx_qt_qspinbox_setrange(QSpinBox * box, int minimum, int maximum) {
	box->setRange(minimum, maximum);
}

void bmx_qt_qspinbox_setsinglestep(QSpinBox * box, int val) {
	box->setSingleStep(val);
}

void bmx_qt_qspinbox_setsuffix(QSpinBox * box, BBString * suffix) {
	box->setSuffix(qStringFromBBString(suffix));
}

int bmx_qt_qspinbox_singlestep(QSpinBox * box) {
	return box->singleStep();
}

BBString * bmx_qt_qspinbox_suffix(QSpinBox * box) {
	return bbStringFromQString(box->suffix());
}

int bmx_qt_qspinbox_value(QSpinBox * box) {
	return box->value();
}


void bmx_qt_qspinbox_setvalue(QSpinBox * box, int value) {
	box->setValue(value);
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
