/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQPen::MaxQPen(const QPen & p)
	: pen(p)
{
}

MaxQPen::~MaxQPen()
{
}

QPen & MaxQPen::Pen() {
	return pen;
}


// *********************************************

MaxQPen * bmx_qt_qpen_create(int style) {
	QPen p((Qt::PenStyle)style);
	return new MaxQPen(p);
}

MaxQPen * bmx_qt_qpen_createwithattributes(MaxQBrush * brush, double width, int style, int cap, int join) {
	QPen p(brush->Brush(), width, (Qt::PenStyle)style, (Qt::PenCapStyle)cap, (Qt::PenJoinStyle)join);
	return new MaxQPen(p);
}

MaxQPen * bmx_qt_qpen_createwithglobalcolor(int color) {
	QPen p((Qt::GlobalColor)color);
	return new MaxQPen(p);
}

MaxQBrush * bmx_qt_qpen_brush(MaxQPen * pen) {
	return new MaxQBrush(pen->Pen().brush());
}

int bmx_qt_qpen_capstyle(MaxQPen * pen) {
	return pen->Pen().capStyle();
}

MaxQColor * bmx_qt_qpen_color(MaxQPen * pen) {
	return new MaxQColor(pen->Pen().color());
}

double bmx_qt_qpen_dashoffset(MaxQPen * pen) {
	return pen->Pen().dashOffset();
}

BBArray * bmx_qt_qpen_dashpattern(MaxQPen * pen) {
	return bbDoubleArrayFromQRealVector(pen->Pen().dashPattern());
}

int bmx_qt_qpen_iscosmetic(MaxQPen * pen) {
	return static_cast<int>(pen->Pen().isCosmetic());
}

int bmx_qt_qpen_issolid(MaxQPen * pen) {
	return static_cast<int>(pen->Pen().isSolid());
}

int bmx_qt_qpen_joinstyle(MaxQPen * pen) {
	return pen->Pen().joinStyle();
}

double bmx_qt_qpen_miterlimit(MaxQPen * pen) {
	return pen->Pen().miterLimit();
}

void bmx_qt_qpen_setbrush(MaxQPen * pen, MaxQBrush * brush) {
	pen->Pen().setBrush(brush->Brush());
}

void bmx_qt_qpen_setcapstyle(MaxQPen * pen, int style) {
	pen->Pen().setCapStyle((Qt::PenCapStyle)style);
}

void bmx_qt_qpen_setcolor(MaxQPen * pen, MaxQColor * color) {
	pen->Pen().setColor(color->Color());
}

void bmx_qt_qpen_setcosmetic(MaxQPen * pen, int cosmetic) {
	pen->Pen().setCosmetic(static_cast<bool>(cosmetic));
}

void bmx_qt_qpen_setdashoffset(MaxQPen * pen, double offset) {
	pen->Pen().setDashOffset(offset);
}

void bmx_qt_qpen_setdashpattern(MaxQPen * pen, BBArray * p) {
	pen->Pen().setDashPattern(qRealVectorFromBBDoubleArray(p));
}

void bmx_qt_qpen_setjoinstyle(MaxQPen * pen, int style) {
	pen->Pen().setJoinStyle((Qt::PenJoinStyle)style);
}

void bmx_qt_qpen_setmiterlimit(MaxQPen * pen, double limit) {
	pen->Pen().setMiterLimit(limit);
}

void bmx_qt_qpen_setstyle(MaxQPen * pen, int style) {
	pen->Pen().setStyle((Qt::PenStyle)style);
}

void bmx_qt_qpen_setwidth(MaxQPen * pen, int width) {
	pen->Pen().setWidth(width);
}

void bmx_qt_qpen_setwidthf(MaxQPen * pen, double width) {
	pen->Pen().setWidthF(width);
}

int bmx_qt_qpen_style(MaxQPen * pen) {
	return pen->Pen().style();
}

int bmx_qt_qpen_width(MaxQPen * pen) {
	return pen->Pen().width();
}

double bmx_qt_qpen_widthf(MaxQPen * pen) {
	return pen->Pen().widthF();
}

void bmx_qt_qpen_free(MaxQPen * pen) {
	delete pen;
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
