/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQGraphicsRectItem::MaxQGraphicsRectItem(BBObject * handle, const QRectF & rect, QGraphicsItem * parent)
	: maxHandle(handle), QGraphicsRectItem(rect, parent)
{
	qgibind(this, handle);
}

MaxQGraphicsRectItem::~MaxQGraphicsRectItem()
{
	qgiunbind(this);
}

// *********************************************


void MaxQGraphicsRectItem::defaultContextMenuEvent(QGraphicsSceneContextMenuEvent * contextMenuEvent) {
	QGraphicsRectItem::contextMenuEvent(contextMenuEvent);
}

void MaxQGraphicsRectItem::defaultDragEnterEvent(QGraphicsSceneDragDropEvent * event) {
	QGraphicsRectItem::dragEnterEvent(event);
}

void MaxQGraphicsRectItem::defaultDragLeaveEvent(QGraphicsSceneDragDropEvent * event) {
	QGraphicsRectItem::dragLeaveEvent(event);
}

void MaxQGraphicsRectItem::defaultDragMoveEvent(QGraphicsSceneDragDropEvent * event) {
	QGraphicsRectItem::dragMoveEvent(event);
}

void MaxQGraphicsRectItem::defaultDropEvent(QGraphicsSceneDragDropEvent * event) {
	QGraphicsRectItem::dropEvent(event);
}

void MaxQGraphicsRectItem::defaultFocusInEvent(QFocusEvent * focusEvent) {
	QGraphicsRectItem::focusInEvent(focusEvent);
}

void MaxQGraphicsRectItem::defaultFocusOutEvent(QFocusEvent * focusEvent) {
	QGraphicsRectItem::focusOutEvent(focusEvent);
}

void MaxQGraphicsRectItem::defaultHoverEnterEvent(QGraphicsSceneHoverEvent * hoverEvent) {
	QGraphicsRectItem::hoverEnterEvent(hoverEvent);
}

void MaxQGraphicsRectItem::defaultHoverLeaveEvent(QGraphicsSceneHoverEvent * hoverEvent) {
	QGraphicsRectItem::hoverLeaveEvent(hoverEvent);
}

void MaxQGraphicsRectItem::defaultHoverMoveEvent(QGraphicsSceneHoverEvent * hoverEvent) {
	QGraphicsRectItem::hoverMoveEvent(hoverEvent);
}

void MaxQGraphicsRectItem::defaultInputMethodEvent(QInputMethodEvent * event) {
	QGraphicsRectItem::inputMethodEvent(event);
}

void MaxQGraphicsRectItem::defaultKeyPressEvent(QKeyEvent * keyEvent) {
	QGraphicsRectItem::keyPressEvent(keyEvent);
}

void MaxQGraphicsRectItem::defaultKeyReleaseEvent(QKeyEvent * keyEvent) {
	QGraphicsRectItem::keyReleaseEvent(keyEvent);
}

void MaxQGraphicsRectItem::defaultMouseDoubleClickEvent(QGraphicsSceneMouseEvent * mouseEvent) {
	QGraphicsRectItem::mouseDoubleClickEvent(mouseEvent);
}

void MaxQGraphicsRectItem::defaultMouseMoveEvent(QGraphicsSceneMouseEvent * mouseEvent) {
	QGraphicsRectItem::mouseMoveEvent(mouseEvent);
}

void MaxQGraphicsRectItem::defaultMousePressEvent(QGraphicsSceneMouseEvent * mouseEvent) {
	QGraphicsRectItem::mousePressEvent(mouseEvent);
}

void MaxQGraphicsRectItem::defaultMouseReleaseEvent(QGraphicsSceneMouseEvent * mouseEvent) {
	QGraphicsRectItem::mouseReleaseEvent(mouseEvent);
}

void MaxQGraphicsRectItem::defaultSceneEvent(QEvent * event) {
	QGraphicsRectItem::sceneEvent(event);
}

void MaxQGraphicsRectItem::defaultSceneEventFilter(QGraphicsItem * watched, QEvent * event) {
	QGraphicsRectItem::sceneEventFilter(watched, event);
}

void MaxQGraphicsRectItem::defaultWheelEvent(QGraphicsSceneWheelEvent * wheelEvent) {
	QGraphicsRectItem::wheelEvent(wheelEvent);
}

// *********************************************

QGraphicsRectItem * bmx_qt_qgraphicsrectitem_create(BBObject * handle, MaxQRectF * rect, QGraphicsItem * parent) {
	return new MaxQGraphicsRectItem(handle, rect->Rect(), parent);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
