/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQCursor::MaxQCursor(const QCursor & c)
	: cursor(c)
{
}

MaxQCursor::~MaxQCursor()
{
}

QCursor & MaxQCursor::Cursor() {
	return cursor;
}


// *********************************************

MaxQCursor * bmx_qt_qcursor_create(int shape) {
	QCursor c((Qt::CursorShape)shape);
	return new MaxQCursor(c);
}

void bmx_qt_qcursor_free(MaxQCursor * cursor) {
	delete cursor;
}

MaxQBitmap * bmx_qt_qcursor_bitmap(MaxQCursor * cursor) {
	return new MaxQBitmap(*cursor->Cursor().bitmap());
}

void bmx_qt_qcursor_hotspot(MaxQCursor * cursor, int * x, int * y) {
	QPoint p(cursor->Cursor().hotSpot());
	*x = p.x();
	*y = p.y();
}

MaxQBitmap * bmx_qt_qcursor_mask(MaxQCursor * cursor) {
	return new MaxQBitmap(*cursor->Cursor().mask());
}

MaxQPixmap * bmx_qt_qcursor_pixmap(MaxQCursor * cursor) {
	return new MaxQPixmap(cursor->Cursor().pixmap());
}

void bmx_qt_qcursor_setshape(MaxQCursor * cursor, int shape) {
	cursor->Cursor().setShape((Qt::CursorShape)shape);
}

int bmx_qt_qcursor_shape(MaxQCursor * cursor) {
	return cursor->Cursor().shape();
}

void bmx_qt_qcursor_pos(int * x, int * y) {
	QPoint p(QCursor::pos());
	*x = p.x();
	*y = p.y();
}

void bmx_qt_qcursor_setpos(int x, int y) {
	QCursor::setPos(x, y);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
