/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQFontInfo::MaxQFontInfo(const QFontInfo & i)
	: info(i)
{
}

MaxQFontInfo::~MaxQFontInfo()
{
}

QFontInfo & MaxQFontInfo::Info() {
	return info;
}


// *********************************************

MaxQFontInfo * bmx_qt_qfontinfo_create(MaxQFont * font) {
	return new MaxQFontInfo(font->Font());
}

int bmx_qt_qfontinfo_bold(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().bold());
}

int bmx_qt_qfontinfo_exactmatch(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().exactMatch());
}

BBString * bmx_qt_qfontinfo_family(MaxQFontInfo * info) {
	return bbStringFromQString(info->Info().family());
}

int bmx_qt_qfontinfo_fixedpitch(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().fixedPitch());
}

int bmx_qt_qfontinfo_italic(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().italic());
}

int bmx_qt_qfontinfo_pixelsize(MaxQFontInfo * info) {
	return info->Info().pixelSize();
}

int bmx_qt_qfontinfo_pointsize(MaxQFontInfo * info) {
	return info->Info().pointSize();
}

double bmx_qt_qfontinfo_pointsizef(MaxQFontInfo * info) {
	return info->Info().pointSizeF();
}

int bmx_qt_qfontinfo_rawmode(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().rawMode());
}

int bmx_qt_qfontinfo_style(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().style());
}

int bmx_qt_qfontinfo_stylehint(MaxQFontInfo * info) {
	return static_cast<int>(info->Info().styleHint());
}

BBString * bmx_qt_qfontinfo_stylename(MaxQFontInfo * info) {
	return bbStringFromQString(info->Info().styleName());
}

int bmx_qt_qfontinfo_weight(MaxQFontInfo * info) {
	return info->Info().weight();
}

void bmx_qt_qfontinfo_free(MaxQFontInfo * info) {
	delete info;
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
