/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------



// *********************************************

int bmx_qt_qabstractbutton_autoexclusive(QAbstractButton * button) {
	return static_cast<int>(button->autoExclusive());
}

int bmx_qt_qabstractbutton_autorepeat(QAbstractButton * button) {
	return static_cast<int>(button->autoRepeat());
}

int bmx_qt_qabstractbutton_autorepeatdelay(QAbstractButton * button) {
	return button->autoRepeatDelay();
}

int bmx_qt_qabstractbutton_autorepeatinterval(QAbstractButton * button) {
	return button->autoRepeatInterval();
}

QButtonGroup * bmx_qt_qabstractbutton_group(QAbstractButton * button) {
	return button->group();
}

void bmx_qt_qabstractbutton_iconsize(QAbstractButton * button, int * w, int * h) {
	QSize s(button->iconSize());
	*w = s.width();
	*h = s.height();
}

int bmx_qt_qabstractbutton_ischeckable(QAbstractButton * button) {
	return static_cast<int>(button->isCheckable());
}

int bmx_qt_qabstractbutton_ischecked(QAbstractButton * button) {
	return static_cast<int>(button->isChecked());
}

int bmx_qt_qabstractbutton_isdown(QAbstractButton * button) {
	return static_cast<int>(button->isDown());
}

void bmx_qt_qabstractbutton_setautoexclusive(QAbstractButton * button, int value) {
	button->setAutoExclusive(static_cast<bool>(value));
}

void bmx_qt_qabstractbutton_setautorepeat(QAbstractButton * button, int value) {
	button->setAutoRepeat(static_cast<bool>(value));
}

void bmx_qt_qabstractbutton_setautorepeatdelay(QAbstractButton * button, int value) {
	button->setAutoRepeatDelay(value);
}

void bmx_qt_qabstractbutton_setautorepeatinterval(QAbstractButton * button, int value) {
	button->setAutoRepeatInterval(value);
}

void bmx_qt_qabstractbutton_setcheckable(QAbstractButton * button, int value) {
	button->setCheckable(static_cast<bool>(value));
}

void bmx_qt_qabstractbutton_setdown(QAbstractButton * button, int value) {
	button->setDown(static_cast<bool>(value));
}

void bmx_qt_qabstractbutton_settext(QAbstractButton * button, BBString * text) {
	button->setText(qStringFromBBString(text));
}

BBString * bmx_qt_qabstractbutton_text(QAbstractButton * button) {
	return bbStringFromQString(button->text());
}

void bmx_qt_qabstractbutton_animateclick(QAbstractButton * button, int msec) {
	button->animateClick(msec);
}

void bmx_qt_qabstractbutton_click(QAbstractButton * button) {
	button->click();
}

void bmx_qt_qabstractbutton_setchecked(QAbstractButton * button, int value) {
	return button->setChecked(static_cast<bool>(value));
}

void bmx_qt_qabstractbutton_seticonsize(QAbstractButton * button, int w, int h) {
	button->setIconSize(QSize(w, h));
}

void bmx_qt_qabstractbutton_toggle(QAbstractButton * button) {
	button->toggle();
}

MaxQIcon *  bmx_qt_qabstractbutton_icon(QAbstractButton * button) {
	return new MaxQIcon(button->icon());
}

void bmx_qt_qabstractbutton_seticon(QAbstractButton * button, MaxQIcon * icon) {
	button->setIcon(icon->Icon());
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
