/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQButtonGroup::MaxQButtonGroup(BBObject * handle, QObject * parent)
	: maxHandle(handle), QButtonGroup(parent)
{
	qbind(this, handle);

	connect(this, SIGNAL(buttonClicked(QAbstractButton *)), SLOT(onButtonClicked(QAbstractButton *)));
	connect(this, SIGNAL(buttonPressed(QAbstractButton *)), SLOT(onButtonPressed(QAbstractButton *)));
	connect(this, SIGNAL(buttonReleased(QAbstractButton *)), SLOT(onButtonReleased(QAbstractButton *)));
}

MaxQButtonGroup::~MaxQButtonGroup()
{
	qunbind(this);
}

void MaxQButtonGroup::onButtonClicked(QAbstractButton * button) {
	_qt_qbuttongroup_QButtonGroup__OnButtonClicked(maxHandle, button);
}

void MaxQButtonGroup::onButtonPressed(QAbstractButton * button) {
	_qt_qbuttongroup_QButtonGroup__OnButtonPressed(maxHandle, button);
}

void MaxQButtonGroup::onButtonReleased(QAbstractButton * button) {
	_qt_qbuttongroup_QButtonGroup__OnButtonReleased(maxHandle, button);
}


// *********************************************

QButtonGroup * bmx_qt_qbuttongroup_create(BBObject * handle, QObject * parent) {
	return new MaxQButtonGroup(handle, parent);
}

void bmx_qt_qbuttongroup_addbutton(QButtonGroup * group, QAbstractButton *button, int id) {
	group->addButton(button, id);
}

QAbstractButton * bmx_qt_qbuttongroup_button(QButtonGroup * group, int id) {
	return group->button(id);
}

QAbstractButton * bmx_qt_qbuttongroup_checkedbutton(QButtonGroup * group) {
	return group->checkedButton();
}

int bmx_qt_qbuttongroup_checkedid(QButtonGroup * group) {
	return group->checkedId();
}

int bmx_qt_qbuttongroup_exclusive(QButtonGroup * group) {
	return static_cast<int>(group->exclusive());
}

int bmx_qt_qbuttongroup_id(QButtonGroup * group, QAbstractButton *button) {
	return group->id(button);
}

void bmx_qt_qbuttongroup_removebutton(QButtonGroup * group, QAbstractButton *button) {
	group->removeButton(button);
}

void bmx_qt_qbuttongroup_setexclusive(QButtonGroup * group, int value) {
	group->setExclusive(static_cast<bool>(value));
}

void bmx_qt_qbuttongroup_setid(QButtonGroup * group, QAbstractButton *button, int id) {
	group->setId(button, id);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
