/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQWidget::MaxQWidget(BBObject * handle, QWidget * parent, Qt::WindowFlags flags)
	: maxHandle(handle), QWidget(parent, flags)
{
	qbind(this, handle);
}

MaxQWidget::~MaxQWidget()
{
	qunbind(this);
}


// *********************************************


QWidget * bmx_qt_qwidget_create(BBObject * handle, QWidget * parent, int f) {
	return new MaxQWidget(handle, parent, bmx_qt_getwindowflags(f));
}

void bmx_qt_qwidget_hide(QWidget * widget) {
	widget->hide();
}

void bmx_qt_qwidget_show(QWidget * widget) {
	widget->show();
}

void bmx_qt_qwidget_setlayout(QWidget * widget, QLayout * layout) {
	widget->setLayout(layout);
}

void bmx_qt_qwidget_setwindowtitle(QWidget * widget, BBString * title) {
	widget->setWindowTitle(qStringFromBBString(title));
}

void bmx_qt_qwidget_showfullscreen(QWidget * widget) {
	widget->showFullScreen();
}

void bmx_qt_qwidget_showmaximized(QWidget * widget) {
	widget->showMaximized();
}

void bmx_qt_qwidget_showminimized(QWidget * widget) {
	widget->showMinimized();
}

void bmx_qt_qwidget_shownormal(QWidget * widget) {
	widget->showNormal();
}

void bmx_qt_qwidget_stackunder(QWidget * widget, QWidget * w) {
	widget->stackUnder(w);
}

void bmx_qt_qwidget_setfixedsize(QWidget * widget, int w, int h) {
	widget->setFixedSize(w, h);
}

void bmx_qt_qwidget_setfixedwidth(QWidget * widget, int w) {
	widget->setFixedWidth(w);
}

void bmx_qt_qwidget_setfocus(QWidget * widget, int reason) {
	widget->setFocus(bmx_qt_getfocusreason(reason));
}

void bmx_qt_qwidget_close(QWidget * widget) {
	widget->close();
}


void bmx_qt_qwidget_update(QWidget * widget) {
	widget->update();
}


void bmx_qt_qwidget_raise(QWidget * widget) {
	widget->raise();
}


void bmx_qt_qwidget_repaint(QWidget * widget) {
	widget->repaint();
}


void bmx_qt_qwidget_setdisabled(QWidget * widget, int disable) {
	widget->setDisabled(static_cast<bool>(disable));
}


void bmx_qt_qwidget_setenabled(QWidget * widget, int value) {
	widget->setEnabled(static_cast<bool>(value));
}


void bmx_qt_qwidget_sethidden(QWidget * widget, int hidden) {
	widget->setHidden(static_cast<bool>(hidden));
}


void bmx_qt_qwidget_setstylesheet(QWidget * widget, BBString * styleSheet) {
	widget->setStyleSheet(qStringFromBBString(styleSheet));
}


void bmx_qt_qwidget_setvisible(QWidget * widget, int visible) {
	widget->setVisible(static_cast<bool>(visible));
}


void bmx_qt_qwidget_setwindowmodified(QWidget * widget, int value) {
	widget->setWindowModified(static_cast<bool>(value));
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
