/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQStackedWidget::MaxQStackedWidget(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QStackedWidget(parent)
{
	qbind(this, handle);
}

MaxQStackedWidget::~MaxQStackedWidget()
{
	qunbind(this);
}

void MaxQStackedWidget::onCurrentChanged(int index) {
	_qt_qstackedwidget_QStackedWidget__OnCurrentChanged(maxHandle, index);
}

void MaxQStackedWidget::onWidgetRemoved(int index) {
	_qt_qstackedwidget_QStackedWidget__OnWidgetRemoved(maxHandle, index);
}

void MaxQStackedWidget::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}


// *********************************************

QStackedWidget * bmx_qt_qstackedwidget_create(BBObject * handle, QWidget * parent) {
	return new MaxQStackedWidget(handle, parent);
}

int bmx_qt_qstackedwidget_addwidget(QStackedWidget * sw, QWidget * widget) {
	return sw->addWidget(widget);
}

int bmx_qt_qstackedwidget_count(QStackedWidget * sw) {
	return sw->count();
}

int bmx_qt_qstackedwidget_currentindex(QStackedWidget * sw) {
	return sw->currentIndex();
}

QWidget * bmx_qt_qstackedwidget_currentwidget(QStackedWidget * sw) {
	return sw->currentWidget();
}

int bmx_qt_qstackedwidget_indexof(QStackedWidget * sw, QWidget * widget) {
	return sw->indexOf(widget);
}

int bmx_qt_qstackedwidget_insertwidget(QStackedWidget * sw, int index, QWidget * widget) {
	return sw->insertWidget(index, widget);
}

void bmx_qt_qstackedwidget_removewidget(QStackedWidget * sw, QWidget * widget) {
	sw->removeWidget(widget);
}

QWidget * bmx_qt_qstackedwidget_widget(QStackedWidget * sw, int index) {
	return sw->widget(index);
}

void bmx_qt_qstackedwidget_setcurrentindex(QStackedWidget * sw, int index) {
	sw->setCurrentIndex(index);
}

void bmx_qt_qstackedwidget_setcurrentwidget(QStackedWidget * sw, QWidget * widget) {
	sw->setCurrentWidget(widget);
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
