/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQDialog::MaxQDialog(BBObject * handle, QWidget * parent, Qt::WindowFlags flags)
	: maxHandle(handle), QDialog(parent, flags)
{
	qbind(this, handle);

	connect(this, SIGNAL(accepted()), SLOT(onAccepted()));
	connect(this, SIGNAL(finished(int)), SLOT(onFinished(int)));
	connect(this, SIGNAL(rejected()), SLOT(onRejected()));
}

MaxQDialog::~MaxQDialog()
{
	qunbind(this);
}

void MaxQDialog::onAccepted() {
	_qt_qdialog_QDialog__OnAccepted(maxHandle);
}

void MaxQDialog::onFinished(int result) {
	_qt_qdialog_QDialog__OnFinished(maxHandle, result);
}

void MaxQDialog::onRejected() {
	_qt_qdialog_QDialog__OnRejected(maxHandle);
}

void MaxQDialog::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}

void MaxQDialog::timerEvent(QTimerEvent * event) {
	_qt_qobject_QObject__timerEvent(maxHandle, event);
}

// *********************************************

QDialog * bmx_qt_qdialog_create(BBObject * handle, QWidget * parent, int flags) {
	return new MaxQDialog(handle, parent, (Qt::WindowFlags)flags);
}

int bmx_qt_qdialog_issizegripenabled(QDialog * dialog) {
	return dialog->isSizeGripEnabled();
}

int bmx_qt_qdialog_result(QDialog * dialog) {
	return dialog->result();
}

void bmx_qt_qdialog_setmodal(QDialog * dialog, int modal) {
	dialog->setModal(static_cast<bool>(modal));
}

void bmx_qt_qdialog_setresult(QDialog * dialog, int i) {
	dialog->setResult(i);
}

void bmx_qt_qdialog_setsizegripenabled(QDialog * dialog, int value) {
	dialog->setSizeGripEnabled(static_cast<bool>(value));
}

void bmx_qt_qdialog_accept(QDialog * dialog) {
	dialog->accept();
}

void bmx_qt_qdialog_done(QDialog * dialog, int r) {
	dialog->done(r);
}

int bmx_qt_qdialog_exec(QDialog * dialog) {
	return dialog->exec();
}

void bmx_qt_qdialog_open(QDialog * dialog) {
	dialog->open();
}

void bmx_qt_qdialog_reject(QDialog * dialog) {
	dialog->reject();
}



// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
