/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQFileInfo::MaxQFileInfo(const QFileInfo & i)
	: info(i)
{
}

MaxQFileInfo::~MaxQFileInfo()
{
}

QFileInfo & MaxQFileInfo::Info() {
	return info;
}


// *********************************************

MaxQFileInfo * bmx_qt_qfileinfo_create(BBString * file) {
	QFileInfo i(qStringFromBBString(file));
	return new MaxQFileInfo(i);
}

MaxQFileInfo * bmx_qt_qfileinfo_createfile(QFile * file) {
	QFileInfo i(*file);
	return new MaxQFileInfo(i);
}

void bmx_qt_qfileinfo_free(MaxQFileInfo * info) {
	delete info;
}

BBString * bmx_qt_qfileinfo_absolutefilepath(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().absoluteFilePath());
}

BBString * bmx_qt_qfileinfo_absolutepath(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().absolutePath());
}

BBString * bmx_qt_qfileinfo_basename(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().baseName());
}

BBString * bmx_qt_qfileinfo_bundlename(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().bundleName());
}

int bmx_qt_qfileinfo_caching(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().caching());
}

BBString * bmx_qt_qfileinfo_canonicalfilepath(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().canonicalFilePath());
}

BBString * bmx_qt_qfileinfo_canonicalpath(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().canonicalPath());
}

BBString * bmx_qt_qfileinfo_completebasename(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().completeBaseName());
}

BBString * bmx_qt_qfileinfo_completesuffix(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().completeSuffix());
}

int bmx_qt_qfileinfo_exists(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().exists());
}

BBString * bmx_qt_qfileinfo_filename(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().fileName());
}

BBString * bmx_qt_qfileinfo_filepath(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().filePath());
}

BBString * bmx_qt_qfileinfo_group(MaxQFileInfo * info) {
	return bbStringFromQString(info->Info().group());
}

uint bmx_qt_qfileinfo_groupid(MaxQFileInfo * info) {
	return info->Info().groupId();
}

int bmx_qt_qfileinfo_isabsolute(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isAbsolute());
}

int bmx_qt_qfileinfo_isbundle(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isBundle());
}

int bmx_qt_qfileinfo_isdir(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isDir());
}

int bmx_qt_qfileinfo_isexecutable(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isExecutable());
}

int bmx_qt_qfileinfo_isfile(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isFile());
}

int bmx_qt_qfileinfo_ishidden(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isHidden());
}

int bmx_qt_qfileinfo_isreadable(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isReadable());
}

int bmx_qt_qfileinfo_isrelative(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isRelative());
}

int bmx_qt_qfileinfo_isroot(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isRoot());
}

int bmx_qt_qfileinfo_issymlink(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isSymLink());
}

int bmx_qt_qfileinfo_iswritable(MaxQFileInfo * info) {
	return static_cast<int>(info->Info().isWritable());
}



// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
