/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQPolygonF::MaxQPolygonF()
{
}

MaxQPolygonF::MaxQPolygonF(const QPolygonF & p)
	: polygon(p)
{
}

MaxQPolygonF::~MaxQPolygonF()
{
}

QPolygonF & MaxQPolygonF::Polygon() {
	return polygon;
}


// *********************************************

MaxQPolygonF * bmx_qt_qpolygonf_create() {
	return new MaxQPolygonF();
}

int bmx_qt_qpolygonf_containspoint(MaxQPolygonF * poly, float x, float y, int fillRule) {
	return static_cast<int>(poly->Polygon().containsPoint(QPointF(x, y), (Qt::FillRule)fillRule));
}

MaxQPolygonF * bmx_qt_qpolygonf_intersected(MaxQPolygonF * poly, MaxQPolygonF * r) {
	return new MaxQPolygonF(poly->Polygon().intersected(r->Polygon()));
}

int bmx_qt_qpolygonf_isclosed(MaxQPolygonF * poly) {
	return static_cast<int>(poly->Polygon().isClosed());
}

int bmx_qt_qpolygonf_isempty(MaxQPolygonF * poly) {
	return static_cast<int>(poly->Polygon().isEmpty());
}

int bmx_qt_qpolygonf_size(MaxQPolygonF * poly) {
	return poly->Polygon().size();
}

MaxQPolygonF * bmx_qt_qpolygonf_subtracted(MaxQPolygonF * poly, MaxQPolygonF *r) {
	return new MaxQPolygonF(poly->Polygon().subtracted(r->Polygon()));
}

void bmx_qt_qpolygonf_translate(MaxQPolygonF * poly, float dx, float dy) {
	poly->Polygon().translate(dx, dy);
}

MaxQPolygonF * bmx_qt_qpolygonf_united(MaxQPolygonF * poly, MaxQPolygonF * r) {
	return new MaxQPolygonF(poly->Polygon().united(r->Polygon()));
}

void bmx_qt_qpolygonf_free(MaxQPolygonF * poly) {
	delete poly;
}

void bmx_qt_qpolygonf_at(MaxQPolygonF * poly, int index, float * x, float * y) {
	QPointF p(poly->Polygon().at(index));
	*x = p.x();
	*y = p.y();
}

void bmx_qt_qpolygonf_clear(MaxQPolygonF * poly) {
	poly->Polygon().clear();
}

void bmx_qt_qpolygonf_append(MaxQPolygonF * poly, float x, float y) {
	poly->Polygon().append(QPointF(x, y));
}

void bmx_qt_qpolygonf_prepend(MaxQPolygonF * poly, float x, float y) {
	poly->Polygon().prepend(QPointF(x, y));
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
