/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQTimer::MaxQTimer(BBObject * handle, QObject * parent)
	: maxHandle(handle), QTimer(parent)
{
	qbind(this, handle);
	
	connect(this, SIGNAL(timeout()), SLOT(onTimeout()));
}

MaxQTimer::~MaxQTimer()
{
	qunbind(this);
}

void MaxQTimer::onTimeout() {
	_qt_qtimer_QTimer__OnTimeout(maxHandle);
}

// *********************************************

QTimer * bmx_qt_qtimer_create(BBObject * handle, QObject * parent) {
	return new MaxQTimer(handle, parent);
}

int bmx_qt_qtimer_interval(QTimer * timer) {
	return timer->interval();
}

int bmx_qt_qtimer_isactive(QTimer * timer) {
	return static_cast<int>(timer->isActive());
}

int bmx_qt_qtimer_issingleshot(QTimer * timer) {
	return static_cast<int>(timer->isSingleShot());
}

void bmx_qt_qtimer_setinterval(QTimer * timer, int msec) {
	timer->setInterval(msec);
}

void bmx_qt_qtimer_setsingleshot(QTimer * timer, int value) {
	timer->setSingleShot(static_cast<bool>(value));
}

int bmx_qt_qtimer_timerid(QTimer * timer) {
	return timer->timerId();
}

void bmx_qt_qtimer_start(QTimer * timer, int msec) {
	timer->start(msec);
}

void bmx_qt_qtimer_stop(QTimer * timer) {
	timer->stop();
}

void bmx_qt_qtimer_free(QTimer * timer) {
	delete timer;
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
