/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQBoxLayout::MaxQBoxLayout(BBObject * handle, QBoxLayout::Direction dir, QWidget * parent)
	: maxHandle(handle), QBoxLayout(dir, parent)
{
	qbind(this, handle);
}

MaxQBoxLayout::MaxQBoxLayout(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QBoxLayout(QBoxLayout::LeftToRight, parent)
{
	qbind(this, handle);
}

MaxQBoxLayout::~MaxQBoxLayout()
{
	qunbind(this);
}


// *********************************************

QBoxLayout * bmx_qt_qboxlayout_create(BBObject * handle, QWidget * parent) {
	return new MaxQBoxLayout(handle, parent);
}

QBoxLayout * bmx_qt_qboxlayout_createlayout(BBObject * handle, int dir, QWidget * parent) {
	return new MaxQBoxLayout(handle, (QBoxLayout::Direction)dir, parent);
}

void bmx_qt_qboxlayout_addwidget(QBoxLayout * layout, QWidget * widget, int stretch, int alignment) {
	layout->addWidget(widget, stretch, bmx_qt_getalignment(alignment));
}

void bmx_qt_qboxlayout_addstretch(QBoxLayout * layout, int stretch) {
	layout->addStretch(stretch);
}

void bmx_qt_qboxlayout_addlayout(QBoxLayout * layout, QLayout * lt, int stretch) {
	layout->addLayout(lt, stretch);
}

void bmx_qt_qboxlayout_addspaceritem(QBoxLayout * layout, QSpacerItem * spacerItem) {
	layout->addSpacerItem(spacerItem);
}

void bmx_qt_qboxlayout_addspacing(QBoxLayout * layout, int size) {
	layout->addSpacing(size);
}

void bmx_qt_qboxlayout_addstrut(QBoxLayout * layout, int size) {
	layout->addStrut(size);
}

int bmx_qt_qboxlayout_direction(QBoxLayout * layout) {
	return layout->direction();
}

void bmx_qt_qboxlayout_insertlayout(QBoxLayout * layout, int index, QLayout * lt, int stretch) {
	layout->insertLayout(index, lt, stretch);
}

void bmx_qt_qboxlayout_insertspaceritem(QBoxLayout * layout, int index, QSpacerItem * spacerItem) {
	layout->insertSpacerItem(index, spacerItem);
}

void bmx_qt_qboxlayout_insertspacing(QBoxLayout * layout, int index, int size) {
	layout->insertSpacing(index, size);
}

void bmx_qt_qboxlayout_insertstretch(QBoxLayout * layout, int index, int stretch) {
	layout->insertStretch(index, stretch);
}

void bmx_qt_qboxlayout_insertwidget(QBoxLayout * layout, int index, QWidget * widget, int stretch, int alignment) {
	layout->insertWidget(index, widget, stretch, (Qt::Alignment)alignment);
}

void bmx_qt_qboxlayout_setdirection(QBoxLayout * layout, int direction) {
	layout->setDirection((QBoxLayout::Direction)direction);
}

void bmx_qt_qboxlayout_setspacing(QBoxLayout * layout, int spacing) {
	layout->setSpacing(spacing);
}

void bmx_qt_qboxlayout_setstretch(QBoxLayout * layout, int index, int stretch) {
	layout->setStretch(index, stretch);
}

int bmx_qt_qboxlayout_setstretchfactor(QBoxLayout * layout, QLayout * widget, int stretch) {
	return static_cast<int>(layout->setStretchFactor(widget, stretch));
}

int bmx_qt_qboxlayout_setstretchfactorwidget(QBoxLayout * layout, QWidget * widget, int stretch) {
	return static_cast<int>(layout->setStretchFactor(widget, stretch));
}

int bmx_qt_qboxlayout_spacing(QBoxLayout * layout) {
	return layout->spacing();
}

int bmx_qt_qboxlayout_stretch(QBoxLayout * layout, int index) {
	return layout->stretch(index);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
