/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQDesktopWidget::MaxQDesktopWidget(BBObject * handle, QDesktopWidget * w)
	: widget(w), MaxQObjectWrapper(handle, w)
{
	doConnections();
}

MaxQDesktopWidget::MaxQDesktopWidget(QDesktopWidget * w)
	: widget(w), MaxQObjectWrapper(w)
{
	maxHandle = _qt_qdesktopwidget_QDesktopWidget___create(widget);
	qbind(widget, maxHandle);

	doConnections();
}

QDesktopWidget * MaxQDesktopWidget::Widget() {
	return widget;
}

void MaxQDesktopWidget::link(QDesktopWidget * w) {
	BBObject * handle = qfind(w);
	
	if (handle == &bbNullObject) {
		MaxQDesktopWidget * widget = new MaxQDesktopWidget(w);
	}
}

MaxQDesktopWidget::~MaxQDesktopWidget()
{
}

void MaxQDesktopWidget::doConnections() {
	connect(widget, SIGNAL(resized(int)), SLOT(onResized(int)));
	connect(widget, SIGNAL(workAreaResized(int)), SLOT(onWorkAreaResized(int)));
	connect(widget, SIGNAL(customContextMenuRequested(const QPoint &)), SLOT(onCustomContextMenuRequested(const QPoint &)));
}

void MaxQDesktopWidget::onResized(int screen) {
	_qt_qdesktopwidget_QDesktopWidget__OnResized(maxHandle, screen);
}

void MaxQDesktopWidget::onWorkAreaResized(int screen) {
	_qt_qdesktopwidget_QDesktopWidget__OnWorkAreaResized(maxHandle, screen);
}

void MaxQDesktopWidget::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}

// *********************************************

MaxQRect * bmx_qt_qdesktopwidget_availablegeometry(QDesktopWidget * dw, int screen) {
	return new MaxQRect(dw->availableGeometry(screen));
}

MaxQRect * bmx_qt_qdesktopwidget_availablegeometrywidget(QDesktopWidget * dw, QWidget * widget) {
	return new MaxQRect(dw->availableGeometry(widget));
}

MaxQRect * bmx_qt_qdesktopwidget_availablegeometryxy(QDesktopWidget * dw, int x, int y) {
	return new MaxQRect(dw->availableGeometry(QPoint(x, y)));
}

int bmx_qt_qdesktopwidget_isvirtualdesktop(QDesktopWidget * dw) {
	return static_cast<int>(dw->isVirtualDesktop());
}

int bmx_qt_qdesktopwidget_numscreens(QDesktopWidget * dw) {
	return dw->numScreens();
}

int bmx_qt_qdesktopwidget_primaryscreen(QDesktopWidget * dw) {
	return dw->primaryScreen();
}

QWidget * bmx_qt_qdesktopwidget_screen(QDesktopWidget * dw, int screen) {
	return dw->screen(screen);
}

MaxQRect * bmx_qt_qdesktopwidget_screengeometry(QDesktopWidget * dw, int screen) {
	return new MaxQRect(dw->screenGeometry(screen));
}

MaxQRect * bmx_qt_qdesktopwidget_screengeometrywidget(QDesktopWidget * dw, QWidget * widget) {
	return new MaxQRect(dw->screenGeometry(widget));
}

MaxQRect * bmx_qt_qdesktopwidget_screengeometryxy(QDesktopWidget * dw, int x, int y) {
	return new MaxQRect(dw->screenGeometry(QPoint(x, y)));
}

int bmx_qt_qdesktopwidget_screennumber(QDesktopWidget * dw, QWidget * widget) {
	return dw->screenNumber(widget);
}

int bmx_qt_qdesktopwidget_screennumberxy(QDesktopWidget * dw, int x, int y) {
	return dw->screenNumber(QPoint(x, y));
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
