/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQWebDatabase::MaxQWebDatabase(QWebDatabase & d)
	: database(d)
{
}

MaxQWebDatabase::~MaxQWebDatabase()
{
}

QWebDatabase & MaxQWebDatabase::Database() {
	return database;
}

// ---------------------------------------------------------------------------------------

MaxQWebSecurityOrigin::MaxQWebSecurityOrigin(const QWebSecurityOrigin & o)
	: origin(o)
{
}

MaxQWebSecurityOrigin::~MaxQWebSecurityOrigin()
{
}

QWebSecurityOrigin & MaxQWebSecurityOrigin::Origin() {
	return origin;
}

// *********************************************

BBString * bmx_qt_qwebdatabase_displayname(MaxQWebDatabase * db) {
	return bbStringFromQString(db->Database().displayName());
}

void bmx_qt_qwebdatabase_expectedsize(MaxQWebDatabase * db, BBInt64 * value) {
	*value = db->Database().expectedSize();
}

BBString * bmx_qt_qwebdatabase_filename(MaxQWebDatabase * db) {
	return bbStringFromQString(db->Database().fileName());
}

BBString * bmx_qt_qwebdatabase_name(MaxQWebDatabase * db) {
	return bbStringFromQString(db->Database().name());
}

MaxQWebSecurityOrigin * bmx_qt_qwebdatabase_origin(MaxQWebDatabase * db) {
	return new MaxQWebSecurityOrigin(db->Database().origin());
}

void bmx_qt_qwebdatabase_size(MaxQWebDatabase * db, BBInt64 * value) {
	*value = db->Database().size();
}

void bmx_qt_qwebdatabase_free(MaxQWebDatabase * db) {
	delete db;
}


// *********************************************

void bmx_qt_qwebsecurityorigin_databasequota(MaxQWebSecurityOrigin * origin, BBInt64 * value) {
	*value = origin->Origin().databaseQuota();
}

void bmx_qt_qwebsecurityorigin_databaseusage(MaxQWebSecurityOrigin * origin, BBInt64 * value) {
	*value = origin->Origin().databaseUsage();
}

BBString * bmx_qt_qwebsecurityorigin_host(MaxQWebSecurityOrigin * origin) {
	return bbStringFromQString(origin->Origin().host());
}

int bmx_qt_qwebsecurityorigin_port(MaxQWebSecurityOrigin * origin) {
	return origin->Origin().port();
}

BBString * bmx_qt_qwebsecurityorigin_scheme(MaxQWebSecurityOrigin * origin) {
	return bbStringFromQString(origin->Origin().scheme());
}

void bmx_qt_qwebsecurityorigin_setdatabasequota(MaxQWebSecurityOrigin * origin, BBInt64 quota) {
	origin->Origin().setDatabaseQuota(quota);
}

void bmx_qt_qwebsecurityorigin_free(MaxQWebSecurityOrigin * origin) {
	delete origin;
}

// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
