/*
  Copyright (c) 2009-2013 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQToolButton::MaxQToolButton(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QToolButton(parent)
{
	qbind(this, handle);
}

MaxQToolButton::~MaxQToolButton()
{
	qunbind(this);
}

void MaxQToolButton::onTriggered(QAction * action) {

}

void MaxQToolButton::onClicked(bool checked) {

}

void MaxQToolButton::onPressed() {

}

void MaxQToolButton::onReleased() {

}

void MaxQToolButton::onToggled(bool checked) {

}

void MaxQToolButton::onCustomContextMenuRequested(const QPoint & pos) {

}


// *********************************************

QToolButton * bmx_qt_qtoolbutton_create(BBObject * handle, QWidget * parent) {
	return new MaxQToolButton(handle, parent);
}

int bmx_qt_qtoolbutton_arrowtype(QToolButton * button) {
	return button->arrowType();
}

int bmx_qt_qtoolbutton_autoraise(QToolButton * button) {
	return static_cast<int>(button->autoRaise());
}

QAction * bmx_qt_qtoolbutton_defaultaction(QToolButton * button) {
	QAction * action = button->defaultAction();
	MaxQAction::link(action);
	return action;
}

QMenu * bmx_qt_qtoolbutton_menu(QToolButton * button) {
	QMenu * menu = button->menu();
	MaxQMenu::link(menu);
	return menu;
}

int bmx_qt_qtoolbutton_popupmode(QToolButton * button) {
	return button->popupMode();
}

void bmx_qt_qtoolbutton_setarrowtype(QToolButton * button, int arrow) {
	return button->setArrowType((Qt::ArrowType)arrow);
}

void bmx_qt_qtoolbutton_setautoraise(QToolButton * button, int enable) {
	return button->setAutoRaise(static_cast<bool>(enable));
}

void bmx_qt_qtoolbutton_setmenu(QToolButton * button, QMenu * menu) {
	return button->setMenu(menu);
}

void bmx_qt_qtoolbutton_setpopupmode(QToolButton * button, int mode) {
	return button->setPopupMode((QToolButton::ToolButtonPopupMode)mode);
}

int bmx_qt_qtoolbutton_toolbuttonstyle(QToolButton * button) {
	return button->toolButtonStyle();
}

void bmx_qt_qtoolbutton_setdefaultaction(QToolButton * button, QAction * action) {
	return button->setDefaultAction(action);
}

void bmx_qt_qtoolbutton_settoolbuttonstyle(QToolButton * button, int style) {
	return button->setToolButtonStyle((Qt::ToolButtonStyle)style);
}

void bmx_qt_qtoolbutton_showmenu(QToolButton * button) {
	return button->showMenu();
}



// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
