/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQEventLoop::MaxQEventLoop(BBObject * handle, QObject * parent)
	: maxHandle(handle), QEventLoop(parent)
{
	qbind(this, handle);
}

MaxQEventLoop::~MaxQEventLoop()
{
	qunbind(this);
}


// *********************************************

QEventLoop::ProcessEventsFlags bmx_qt_qeventloop_geteventflags(int f) {
	QEventLoop::ProcessEventsFlags flags;

	if (f & 0x0001) flags |= QEventLoop::ExcludeUserInputEvents;
	if (f & 0x0002) flags |= QEventLoop::ExcludeSocketNotifiers;
	if (f & 0x0004) flags |= QEventLoop::WaitForMoreEvents;
	
	return flags;
}

// *********************************************


QEventLoop * bmx_qt_qeventloop_create(BBObject * handle, QObject * parent) {
	return new MaxQEventLoop(handle, parent);
}

int bmx_qt_qeventloop_exec(QEventLoop * eventloop, int flags) {
	return eventloop->exec(bmx_qt_qeventloop_geteventflags(flags));
}

void bmx_qt_qeventloop_exit(QEventLoop * eventloop, int returnCode) {
	eventloop->exit(returnCode);
}

int bmx_qt_qeventloop_isrunning(QEventLoop * eventloop) {
	return static_cast<int>(eventloop->isRunning());
}

int bmx_qt_qeventloop_processevents(QEventLoop * eventloop, int flags) {
	return eventloop->processEvents(bmx_qt_qeventloop_geteventflags(flags));
}

void bmx_qt_qeventloop_processeventstime(QEventLoop * eventloop, int flags, int maxTime) {
	eventloop->processEvents(bmx_qt_qeventloop_geteventflags(flags), maxTime);
}

void bmx_qt_qeventloop_wakeup(QEventLoop * eventloop) {
	eventloop->wakeUp();
}

void bmx_qt_qeventloop_quit(QEventLoop * eventloop) {
	eventloop->quit();
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
