/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQProgressBar::MaxQProgressBar(BBObject * handle, QWidget * parent)
	: maxHandle(handle), QProgressBar(parent)
{
	qbind(this, handle);
	
	connect(this, SIGNAL(valueChanged(int)), SLOT(onValueChanged(int)));
	connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), SLOT(onCustomContextMenuRequested(const QPoint &)));
}

MaxQProgressBar::~MaxQProgressBar()
{
	qunbind(this);
}

void MaxQProgressBar::onValueChanged(int value) {
	_qt_qprogressbar_QProgressBar__OnValueChanged(maxHandle, value);
}

void MaxQProgressBar::onCustomContextMenuRequested(const QPoint & pos) {
	_qt_qwidget_QWidget__OnCustomContextMenuRequested(maxHandle, pos.x(), pos.y());
}

// *********************************************

QProgressBar::Direction bmx_qt_getprogressbardirection(int dir) {
	switch (dir) {
		case 0:
			return QProgressBar::TopToBottom;
		case 1:
			return QProgressBar::BottomToTop;
	}
	
	return QProgressBar::TopToBottom;
}


QProgressBar * bmx_qt_qprogressbar_create(BBObject * handle, QWidget * parent) {
	return new MaxQProgressBar(handle, parent);
}

int bmx_qt_qprogressbar_alignment(QProgressBar * bar) {
	return static_cast<int>(bar->alignment());
}

BBString * bmx_qt_qprogressbar_format(QProgressBar * bar) {
	return bbStringFromQString(bar->format());
}

int bmx_qt_qprogressbar_invertedappearance(QProgressBar * bar) {
	return static_cast<int>(bar->invertedAppearance());
}

int bmx_qt_qprogressbar_istextvisible(QProgressBar * bar) {
	return static_cast<int>(bar->isTextVisible());
}

int bmx_qt_qprogressbar_maximum(QProgressBar * bar) {
	return bar->maximum();
}

int bmx_qt_qprogressbar_minimum(QProgressBar * bar) {
	return bar->minimum();
}

int bmx_qt_qprogressbar_orientation(QProgressBar * bar) {
	return static_cast<int>(bar->orientation());
}

void bmx_qt_qprogressbar_setalignment(QProgressBar * bar, int alignment) {
	bar->setAlignment(bmx_qt_getalignment(alignment));
}

void bmx_qt_qprogressbar_setformat(QProgressBar * bar, BBString * format) {
	bar->setFormat(qStringFromBBString(format));
}

void bmx_qt_qprogressbar_setinvertedappearance(QProgressBar * bar, int invert) {
	bar->setInvertedAppearance(static_cast<bool>(invert));
}

void bmx_qt_qprogressbar_settextdirection(QProgressBar * bar, int textDirection) {
	bar->setTextDirection(bmx_qt_getprogressbardirection(textDirection));
}

void bmx_qt_qprogressbar_settextvisible(QProgressBar * bar, int visible) {
	bar->setTextVisible(static_cast<bool>(visible));
}

BBString * bmx_qt_qprogressbar_text(QProgressBar * bar) {
	return bbStringFromQString(bar->text());
}

int bmx_qt_qprogressbar_textdirection(QProgressBar * bar) {
	return static_cast<int>(bar->textDirection());
}

int bmx_qt_qprogressbar_value(QProgressBar * bar) {
	return bar->value();
}

void bmx_qt_qprogressbar_reset(QProgressBar * bar) {
	bar->reset();
}

void bmx_qt_qprogressbar_setmaximum(QProgressBar * bar, int maximum) {
	bar->setMaximum(maximum);
}

void bmx_qt_qprogressbar_setminimum(QProgressBar * bar, int minimum) {
	bar->setMinimum(minimum);
}

void bmx_qt_qprogressbar_setorientation(QProgressBar * bar, int orientation) {
	bar->setOrientation(bmx_qt_getorientation(orientation));
}

void bmx_qt_qprogressbar_setrange(QProgressBar * bar, int minimum, int maximum) {
	bar->setRange(minimum, maximum);
}

void bmx_qt_qprogressbar_setvalue(QProgressBar * bar, int value) {
	bar->setValue(value);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
