/*
  Copyright (c) 2009 Bruce A Henderson
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/ 

#include "glue.h"

// ---------------------------------------------------------------------------------------

MaxQToolBar::MaxQToolBar(BBObject * handle, QToolBar * tb)
	: toolBar(tb), MaxQObjectWrapper(handle, tb)
{
	doConnections();
}

MaxQToolBar::MaxQToolBar(QToolBar * tb)
	: toolBar(tb), MaxQObjectWrapper(tb)
{
	maxHandle = _qt_qtoolbar_QToolBar___create(tb);
	qbind(tb, maxHandle);

	doConnections();
}

MaxQToolBar::~MaxQToolBar()
{
}

void MaxQToolBar::doConnections() {
	connect(toolBar, SIGNAL(actionTriggered(QAction *)), SLOT(onActionTriggered(QAction *)));
	connect(toolBar, SIGNAL(allowedAreasChanged(Qt::ToolBarAreas)), SLOT(onAllowedAreasChanged(Qt::ToolBarAreas)));
	connect(toolBar, SIGNAL(iconSizeChanged(const QSize &)), SLOT(onIconSizeChanged(const QSize &)));
	connect(toolBar, SIGNAL(movableChanged(bool)), SLOT(onMovableChanged(bool)));
	connect(toolBar, SIGNAL(orientationChanged(Qt::Orientation)), SLOT(onOrientationChanged(Qt::Orientation)));
	connect(toolBar, SIGNAL(toolButtonStyleChanged(Qt::ToolButtonStyle)), SLOT(onToolButtonStyleChanged(Qt::ToolButtonStyle)));
	connect(toolBar, SIGNAL(customContextMenuRequested(const QPoint &)), SLOT(onCustomContextMenuRequested(const QPoint &)));
}

QToolBar * MaxQToolBar::ToolBar() {
	return toolBar;
}

void MaxQToolBar::link(QToolBar * tb) {
	BBObject * handle = qfind(tb);
	
	if (handle == &bbNullObject) {
		MaxQToolBar * toolbar = new MaxQToolBar(tb);
	}
}


void MaxQToolBar::onActionTriggered(QAction * action) {

}

void MaxQToolBar::onAllowedAreasChanged(Qt::ToolBarAreas allowedAreas) {

}

void MaxQToolBar::onIconSizeChanged(const QSize & iconSize) {

}

void MaxQToolBar::onMovableChanged(bool movable) {

}

void MaxQToolBar::onOrientationChanged(Qt::Orientation orientation) {

}

void MaxQToolBar::onToolButtonStyleChanged(Qt::ToolButtonStyle toolButtonStyle) {

}

void MaxQToolBar::onCustomContextMenuRequested(const QPoint & pos) {

}


// *********************************************

QToolBar * bmx_qt_qtoolbar_create(BBObject * handle, QWidget * parent) {
	MaxQToolBar * tb = new MaxQToolBar(handle, new QToolBar(parent));
	return tb->ToolBar();
}

void bmx_qt_qtoolbar_addwidget(QToolBar * tb, QWidget * widget) {
	tb->addWidget(widget);
}


// NOTES :
// The moc4glue.cpp file is generated by running :  moc.sh
// It generates the custom Signal/Slot handler code that Qt uses.
// The file only needs to be re-generated whenever a new slot is added/changed to a class,
// or a new class includes the Q_OBJECT macro.
// Oh.. and it NEEDS to be at the bottom of this file, because of declarations and whatnot.

#include "moc4glue.cpp"
